name: 'Checker completed tasks action'
description: 'Checker completed tasks action.'
author: 'asmyshlyaev177'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
branding:
  icon: 'check-square'
  color: 'green'
